apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo-deployment
spec:
  selector:
    matchLabels:
      app: argocd-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: argocd-demo
    spec:
      containers:
      - name: argocd-demo
        image: phattarin/argocd-demo:1.0
        ports:
        - containerPort: 3000
