# apiVersion: v1
# kind: Service
# metadata:
#   name: argocd-demo-service
# spec:
#   selector:
#     app: argocd-demo
#   ports:
#   - port: 3000
#     protocol: TCP
#     targetPort: 3000

apiVersion: v1
kind: Service
metadata:
  name: argocd-demo-service
  namespace: argocd-demo
spec:
  type: NodePort
  selector:
    app: argocd-demo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30037
